version: '3.3'

services:


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2754
      POSTGRES_DB: payment_api



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
